name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: build
        run: |
          mkdir build
          cd build/
          cmake ..
          make

